# Generated by Django 4.1.7 on 2023-10-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='boot_space',
            field=models.CharField(default=371, max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='max_torque',
            field=models.CharField(default='90 Nm @ 3, 500 rpm', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=27.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='power',
            field=models.CharField(default='67 bhp @ 6, 000 rpm', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seating_capacity',
            field=models.IntegerField(default=5),
        ),
    ]
