# Generated by Django 4.1.7 on 2023-08-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='carmodel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='carbrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cardata.carbrand'),
        ),
    ]
