# Generated by Django 4.1.7 on 2023-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0002_alter_carmodel_boot_space_alter_carmodel_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='boot_space',
            field=models.CharField(default='371 liters', max_length=50),
        ),
    ]
