# Generated by Django 4.1.7 on 2023-08-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0002_carmodel_carmodel_alter_carmodel_carbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarIDE', models.PositiveIntegerField()),
                ('Carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cardata.carbrand')),
                ('Carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cardata.carmodel')),
            ],
        ),
    ]
