# Generated by Django 4.2.4 on 2023-08-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0003_cardata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardata',
            old_name='CarIDE',
            new_name='carIDE',
        ),
        migrations.RenameField(
            model_name='cardata',
            old_name='Carbrand',
            new_name='carbrand',
        ),
        migrations.RenameField(
            model_name='cardata',
            old_name='Carmodel',
            new_name='carmodel',
        ),
    ]
