# Generated by Django 4.1.7 on 2023-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0003_alter_carmodel_boot_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
