# Generated by Django 4.1.7 on 2023-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0004_alter_carmodel_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='boot_space',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='max_torque',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='mileage',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='power',
            field=models.CharField(max_length=50),
        ),
    ]
