# Generated by Django 4.2.4 on 2023-08-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0005_alter_cardata_carbrand_alter_cardata_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='carbrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cardata.carbrand'),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='carmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cardata.carmodel'),
        ),
    ]
