# Generated by Django 4.1.7 on 2023-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0007_alter_cardata_carbrand_alter_cardata_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='caryear',
            field=models.IntegerField(choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='carIDE',
            field=models.PositiveIntegerField(choices=[(100000, 1), (200000, 2), (300000, 3), (400000, 4), (500000, 5), (600000, 6), (700000, 7), (800000, 8), (900000, 9), (1000000, 10)]),
        ),
    ]
