# Generated by Django 4.1.7 on 2023-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0009_cardata_fuletype_alter_cardata_caryear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='fuletype',
            field=models.CharField(choices=[('CNG', 'CNG'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='', max_length=6),
        ),
    ]
