# Generated by Django 4.1.7 on 2023-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0010_alter_cardata_fuletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='', max_length=9),
        ),
    ]
