# Generated by Django 4.1.7 on 2023-08-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0011_cardata_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='kilometers',
            field=models.IntegerField(choices=[(10000, 10000), (20000, 20000), (30000, 30000), (40000, 40000), (50000, 50000), (60000, 60000), (70000, 70000), (80000, 80000), (90000, 90000), (100000, 100000), (110000, 110000), (120000, 120000), (130000, 130000), (140000, 140000), (150000, 150000)], default=0),
        ),
    ]
