# Generated by Django 4.1.7 on 2023-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0012_cardata_kilometers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='ownership',
            field=models.CharField(choices=[('', ''), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('dealer', 'dealer')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='kilometers',
            field=models.IntegerField(choices=[('', ''), (10000, 10000), (20000, 20000), (30000, 30000), (40000, 40000), (50000, 50000), (60000, 60000), (70000, 70000), (80000, 80000), (90000, 90000), (100000, 100000), (110000, 110000), (120000, 120000), (130000, 130000), (140000, 140000), (150000, 150000)], default=0),
        ),
    ]
