# Generated by Django 4.1.7 on 2023-08-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0013_cardata_ownership_alter_cardata_kilometers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
