# Generated by Django 4.2.4 on 2023-08-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0016_alter_cardata_car_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardata',
            name='car_images',
        ),
    ]
