# Generated by Django 4.2.4 on 2023-08-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0017_remove_cardata_car_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='car_images',
            field=models.FileField(default='', upload_to='CarImages'),
        ),
    ]
