# Generated by Django 4.1.7 on 2023-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0018_cardata_car_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CarImages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardata',
            name='car_images',
        ),
        migrations.AddField(
            model_name='cardata',
            name='images',
            field=models.ManyToManyField(related_name='cars', to='Cardata.carimage'),
        ),
    ]
