# Generated by Django 4.1.7 on 2023-08-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0020_remove_cardata_images_cardata_image_delete_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='image',
            field=models.ImageField(default='', upload_to='CarImages'),
        ),
    ]
